### ISSUE TITLE
FR06. Исправить минимальную сумму платежа

### ISSUE THREAD

**Issue by bifrurcated** [DmitryVorotilov/merge_xml#4]
- [ ] Минимальная сумма платежа в документе должна быть больше или равна 10.00 рублям. Также система выводит соответствующее сообщение об ошибке в UI, если сумма меньше 10.00 рублей: “Минимальная сумма платежа 10.00 руб.”. 
- [ ] Добавить unit или integration тесты

**Comment by thekanas** [comment]
взял в работу
