### ISSUE TITLE
FR06. Добавить проверку на код валюты

### ISSUE THREAD

**Issue by bifrurcated** [DmitryVorotilov/merge_xml#5]
- [ ] Код валюты в платежном документе может быть только 810. Также система выводит соответствующее сообщение об ошибке в UI, если код валюты не соответствует 810 : “Допустимое значение кода валюты 810”.  
- [ ] Добавить unit или integration тесты.

**Comment by ribkavmore** [comment]
взяла в работу

**Comment by ribkavmore** [comment]
https://github.com/DmitryVorotilov/merge_xml/pull/8
